Repository rustformers/llm, pull requests merged in 2023-06, with the labels that each got.

#311 Implement Metal support
  Cargo.lock
  Cargo.toml
  binaries/llm-cli/src/cli_args.rs
  binaries/llm-cli/src/main.rs
  crates/ggml/Cargo.toml
  crates/ggml/src/context.rs
  crates/ggml/src/lib.rs
  crates/ggml/src/metal.rs
  crates/ggml/sys/build.rs
  crates/llm-base/Cargo.toml
  crates/llm-base/src/inference_session.rs
  crates/llm-base/src/lib.rs
  crates/llm-base/src/loader.rs
  crates/llm-base/src/lora.rs
  crates/llm-base/src/model/common.rs
  crates/llm-base/src/model/mod.rs
  crates/llm/examples/embeddings.rs
  crates/models/bloom/src/lib.rs
  crates/models/gpt2/src/lib.rs
  crates/models/gptj/src/lib.rs
  crates/models/gptneox/src/lib.rs
  crates/models/llama/src/lib.rs
  crates/models/mpt/Cargo.toml
  crates/models/mpt/src/lib.rs
  doc/CONTRIBUTING.md
  doc/known-good-models.md
Labels: topic:backend-support

#328 fix(metal): patch ggml-metal.m with shader code
  crates/ggml/sys/build.rs
Labels: topic:backend-support, os:macos

#329 feat: automatically run checks before commit
  .github/workflows/rust.yml
  .rusty-hook.toml
  Cargo.lock
  binaries/llm-cli/Cargo.toml
  binaries/precommit-check/Cargo.toml
  binaries/precommit-check/README.md
  binaries/precommit-check/src/main.rs
  doc/CONTRIBUTING.md
Labels: meta:maintenance

#313 Add Falcon Support
  Cargo.lock
  binaries/llm-cli/Cargo.toml
  binaries/llm-cli/src/cli_args.rs
  binaries/llm-cli/src/main.rs
  binaries/precommit-check/src/main.rs
  crates/llm/Cargo.toml
  crates/llm/src/lib.rs
  crates/models/falcon/Cargo.toml
  crates/models/falcon/src/lib.rs
Labels: topic:model-support
